app:
  jwt:
    secret: ${JWT_SECRET:your-secret-key}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds
    refresh-token:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds 